version: 2
jobs:
  build:
    
    working_directory: ~/WebAutomationSuite

    docker:
      - image: circleci/web-automation:firstimage
      

    steps:

      - checkout

      - restore_cache:
          key: WebAutomationSuite-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: WebAutomationSuite-{{ checksum "pom.xml" }}
      
      - run: mvn clean test -DsuiteXmlFile=testng.xml
      
      - store_artifacts:
          path: ./WebAutomationSuite/TestReport
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - branch_one
              only:
                - master