version: 2
jobs:
  build:
    working_directory: ~/WebAutomationTemplate
    docker:
      - image: sureifylabs/sureify-automation:firstimage
    steps:

      - checkout

      - restore_cache:
          key: WebAutomationTemplate -{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: WebAutomationTemplate -{{ checksum "pom.xml" }}
      
      - run: mvn clean test -DsuiteXmlFile=testng.xml
      
      - store_artifacts:
          path: TestReport
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - branch_one
              