# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: WebAutoamtion CI Job

on:
  pull_request:
  push:
    branches: 
      - master
      - branch_one 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
   
    - name: Install Chrome and Firefox
      run: |
        sudo apt install google-chrome-stable
        sudo apt-get install firefox
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
          name: test report
          path: TestReport
